= Reflections: The Shipping News

NOTE: This is the first in a series of posts I'm planning on doing after finishing each book of fiction that I read. Depending on a group of factors, these posts may vary wildly in length, content, and form. The goal is to force myself to formulate my thoughts about the book, which will help me remember it in the future. Since I wasn't taking detailed notes I won't have excerpts for this one. In the future, expect quotes.

===== On the Lyrical Sentences
Much has been said about Proulx's distinctive writing style. She tends to write her short sentences as fragments, often by witholding pronouns or prepositions. It makes her prose stand out, which I guess is a good thing when clearly her goal is to be a literary writer. This is readily apparent in the course of her book, where she uses so much figurative language that some of her similes and metaphors are doomed to fail. Clearly the various award jurists were enchanted by her prose. Certainly, there are many bright spots. What worries me is the obsession over this type of poetic prose, often to the point of elevation over what one might call unmannered prose. Mannered writers include the likes Hemingway, McCarthy (especially his more recent books), David Foster Wallace, and Junot Diaz. What I mean by this is that from a page, often even a sentence, anyone familiar with the author's work could identify it on style alone. Now, I don't consider mannered writing to be inherently good or bad, (John Gardner warns against it in _The Art of Fiction_). But to me, at it's heart the best fiction is about character and story, and an appropriate dusting of symbol and theme. The masterpieces of fiction that survive for decades rarely hang on because of their beautiful sentences. Poems maybe, but rarely prose. It is only our true stylistic masters, like the ones I named above, who leverage their manner so well that it elevates them into the canon. (It's hard to argue that DFW isn't at least on the road to classic-dom, and I fully expect Diaz to be there with him. Hemingway and McCarthy, of course, are already there). But these writers make up a minority of the greats, and it's for a reason. Bad mannered writing is usually even worse than bad 'standard prose,' or whatever you want to call it. 

This is beacuse it's easy for style to overwhelm and distract from what Gardner calls the 'fictive dream,' that kind of movie-image that runs in one's head as they read. The rereading of sentence, the unraveling of a clumsy metaphor, or the mind-numbing slogging through a list of descriptions all pulled me out of the dream while reading _The Shipping News_. But when the sentences flowed, creating rhythms and conjuring imagines in my mind, when the style was at its best, the feeling welled up in me, and moved me. This is the gamble the mannered writer takes, and for me personally, I think it worked for what she was trying to create. A long, lyrical book like this is bound to miss from time to time, and it certainly did. But I felt by the end that I had been treated by a long gaze into Proulx's mind, because it never felt inauthentic. I think she just thinks and writes this way. 
    
===== What Happens?
NOTE: Spoilers lie ahead.
	