= Reflections: The Shipping News
:hp-tags: Book thoughts

NOTE: This is the first in a series of posts I'm planning to write after finishing a book of fiction that I read. Or, if just a single story moves me so, I'll write one on just that. These posts may vary wildly in length, content, and form. The aim is more to force myself to formulate my thoughts the reading, than to make some grand point or persuade someone to read (or not to read) the book. Since I'm bad at annotating, I won't have excerpts for this one. In the future, hopefully I'll do my due dilligence and excerpt quotes.

===== On the Lyrical Sentences

Much has been said about Proulx's distinctive writing style. She tends to write her short sentences as fragments, often by witholding pronouns or prepositions. It makes her prose stand out, which I guess is a good thing when clearly her goal is to be a literary writer. This is readily apparent in the course of her book, where she uses so much figurative language that some of her similes and metaphors are doomed to fail. Clearly the various award jurists were enchanted by her prose. Certainly, there are many bright spots. What worries me is the obsession over this type of poetic prose, often to the point of elevation over what one might call unmannered prose. Mannered writers include the likes Hemingway, McCarthy (especially his more recent books), David Foster Wallace, and Junot Diaz. What I mean by this is that from a page, often even a sentence, anyone familiar with the author's work could identify it on style alone. Now, I don't consider mannered writing to be inherently good or bad, (John Gardner warns against it in _The Art of Fiction_). But to me, at it's heart the best fiction is about character and story, and an appropriate dusting of symbol and theme. The masterpieces of fiction that survive for decades rarely hang on because of their beautiful sentences. Poems maybe, but rarely prose. It is only our true stylistic masters, like the ones I named above, who leverage their manner so well that it elevates them into the canon. (It's hard to argue that DFW isn't at least on the road to classic-dom, and I fully expect Diaz to be there with him. Hemingway and McCarthy, of course, are already there). But these writers make up a minority of the greats, and it's for a reason. Bad mannered writing is usually even worse than bad 'standard prose,' or whatever you want to call it. 

This is beacuse it's easy for style to overwhelm and distract from what Gardner calls the 'fictive dream,' that kind of movie-image that runs in one's head as they read. The rereading of sentence, the unraveling of a clumsy metaphor, or the mind-numbing slogging through a list of descriptions all pulled me out of the dream while reading _The Shipping News_. But when the sentences flowed, creating rhythms and conjuring imagines in my mind, when the style was at its best, the feeling welled up in me, and moved me. This is the gamble the mannered writer takes, and for me personally, I think it worked for what she was trying to create. A long, lyrical book like this is bound to miss from time to time, and it certainly did. But I felt by the end that I had been treated by a long gaze into Proulx's mind, because it never felt inauthentic. I think she just thinks and writes this way.
===== More Sentence Stuff
When I finished _The Shipping News_, a feeling struck me I often feel when reading contemporary literary fiction, whether novels or short stories. I don't want to open the "What has the proliferation of MFA programs done to American fiction" can of worms too far here, but would like to argue one thing: basically every literary fiction writer today, anyone we might vote into the pantheon of contemporary fiction writers who've "made it" (Franzen, Diaz, Chabon, Eggers) write very polished, good sentences. And I'm sure if you pick up any of the novels to make the recently announced First Novel Prize Longlist, you'd find the same thing: sharply chosen metaphors, active verbs, etc. Read any book "on writing" and you'll learn that the passive voice drags one foot into hell and adverbs drag the other. This advice is correct, at least the vast majority of the time, so it makes sense when writing a book that is target at novice writers, the majority of whom will be either bad or at the lower end of competent, to teach the basics. And to a certain extent, undergrad creative writing programs and MFA programs have to do the same thing. Because, after all, it's easy to teach grammar. It's at least possible to teach sentence structure and such. In my opinion what's hard to each are the nebulous things, namely four: character, plot/story (how about we define it: what happens to the characters during the book), theme, and symbol.

I'm only going to focus on the first two, because no consensus, or even anything resembling consensus agrees on whether themes or symbols, or motifs, or whatever really matter, or how much they should matter, or whether they even really exist. But finding someone who reads seriously and doesn't care about character, or doesn't care about story, is probably either the kind of overly obsessive academic that thinks (at least in his heart), that the real point of literatary criticism is to feel superior, or instead they should probably be teaching poetry. Because there, sure, throw it out the window. But novels (and short stories) are about people, and the things that happen to them. 

===== What about the meat? (spoilers)

Circling back around to _The Shipping News_, I thought that the characters were persuasive, but found the action lacking a certain amount. Regarding character, I mostly use my gut. If the characters feel real, I tend to believe them. There are definitely readers out there with more discerning tastes a la characters. The characters need to have some basic consistency of action, and I think one of the things that writers get in trouble with is forcing stereotypical obstacles onto otherwise interesting characters. This was certainly my feeling with _The Shipping News_. The main plot, to me at least, has to do with Quoyle getting over his destructive, promiscuous wife. This is his obstacle to happiness. He doesn't really struggle finding a job or excelling at his job in Killick-Claw. Instead, although Proulx paints a pretty bleak picture of Quoyle's intellgence and general working capabilities at the beginning of the book, he flourishes at the _Gammy Bird_, rising to managing editor by the end of the novel. Instead it's his slow process of getting over the prurient, somatic love he felt for Petal. But even in this case it's apparent from very early in the book (at least to me), that he's found the perfect partner in this quest, Wavey Prouse, and their getting together developed so slowly and obviously that even a minor character (Wavey's uncle) complains about it, channeling my emotion at the time. I was frustrated by the book because I wanted to root for Quoyle. He seemed like a legitimately good guy, so well intentioned and well meaning, but there was never really much at stake for him. Sure, he took a big risk by driving his two daughters up there with an aunt he barely knew, but all the bad things that happened (his near-drowning, the house blowing away at the storm being two) never left much in jeopardy, and both (especially the capsize) were foreshadowed to death, which took away much element of surprise.

Perhaps the struggle of the Aunt felt a little bit more palpable. The newspaper men talk about sexual abuse so often that it seemed inevitable that some central character would have a story. Lucklily Bunny and Sunshine appear to escape the worst of it before Quoyle can steal them away to Newfoundland, but then the reveal of the Aunt's abuse at the hands of her brother (Quoyle's father) fell flat to me. First, because the father isn't a character in the book. His brief appearance in the flashback made him feel more like a spirit of pure evil, and really took away from any kind of nuance in the issue. I don't think Proulx ever gives a satisfying answer to the question "Why is there so much sexual abuse, especially by family members here?" Additionally, I feel like there are so many plots out there involving women and girls struggling to overcome sexual violence that to me it's beginning to verge on cliché. Now of course, sexual violence is a serious issue, and literature can certainly attempt to bring those issues to light, but when every female character is abused, and it doesn't enhance the story or the character beyond "a bad thing happened," in my opinion it flattens the character, and weakens the fiction's overall attempt at some kind of truth or unity or aesthetic whatever we might want from it.

===== Conclusion
NOTE: I'm not planning on grading books, or even giving clear reviews like: this book is bad, or this book is good. This is mostly because value judging art is hard, and way beyond my capabilities at this juncture. To me it is no light thing to take someone's work of art, that they struggled with and completed and presented it to the world, and to pick out a weak paragraph or two and say, wow this is trash. Also, because if I draw any strong conclusions like that, I'm sure you can find someone without much trouble that feels the exact opposite.

So, then, I overall think _The Shipping News_ is, like every work of art, an imperfect triumph. I liked the setting, the characters (especially Quoyle, but also most of the side characters), and enjoyed the best of the language. I struggled at times when I felt like the language took away from the fictive dream, and obfuscated the action or blocked me from understanding the character. Now, I'm not saying Proulx should write her next book in the style of Carver. She accomplishes things here that he never could, and that is primarily a mood. A feeling of rural discovery, sometimes a feeling of being caught in a storm. A book that plays up it's strengths well.